name: ChatterBot
main: me.xTDKx.CB.ChatterBot
version: 1.5
author: xTDKx
commands:
  cb:
    description: ChatterBot command.
  chatterbot:
    description: ChatterBot command.
  cbassign:
    description: ChatterBot assign command.
  chatterbotassign:
    description: ChatterBot assign command.
permissions:
  chatterbot.use:
    description: Usage permission for ChatterBot
    default: true
  chatterbot.admin:
    description: Permission to assign ChatterBot
    default: op