#########################
##      ChatterBot     ##
#########################

# Name displayed in ChatterBot's messages
ChatterBot-Name: [%ChatterBot-Name%]

# Format in which ChatterBot speaks
ChatterBot-Format: [%ChatterBot-Format%]

# Should messages players send ChatterBot be shown publicly?
Loud-Mode: [%Loud-Mode%]

# What is shown when a player ChatterBot a question (while on loud mode)
Loud-Format: [%Loud-Format%]
